-- MySQL Script generated by MySQL Workbench
-- Sun 30 Oct 2016 12:08:01 PM WIB
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lberepo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lberepo` ;

-- -----------------------------------------------------
-- Schema lberepo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lberepo` DEFAULT CHARACTER SET utf8 ;
USE `lberepo` ;

-- -----------------------------------------------------
-- Table `lberepo`.`lab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lberepo`.`lab` ;`1`

CREATE TABLE IF NOT EXISTS `lberepo`.`lab` (
  `id_lab` INT NOT NULL AUTO_INCREMENT,
  `nama_lab` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_lab`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lberepo`.`bidang_lbe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lberepo`.`bidang_lbe` ;

CREATE TABLE IF NOT EXISTS `lberepo`.`bidang_lbe` (
  `id_bidang` INT NOT NULL,
  `nama_bidang` VARCHAR(45) NOT NULL,
  `id_lab` INT NOT NULL,
  PRIMARY KEY (`id_bidang`),
  INDEX `fk_bidang_lbe_lab_idx` (`id_lab` ASC),
  CONSTRAINT `fk_bidang_lbe_lab`
    FOREIGN KEY (`id_lab`)
    REFERENCES `lberepo`.`lab` (`id_lab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lberepo`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lberepo`.`user` ;

CREATE TABLE IF NOT EXISTS `lberepo`.`user` (
  `nrp_user` CHAR(11) NOT NULL,
  `nama_user` VARCHAR(100) NOT NULL,
  `noHp_user` CHAR(14) NOT NULL,
  `line_user` VARCHAR(20) NULL,
  `password_user` VARCHAR(45) NOT NULL,
  `role_user` INT NOT NULL DEFAULT 2,
  `id_bidang` INT NULL,
  `id_lab` INT NOT NULL,
  PRIMARY KEY (`nrp_user`),
  INDEX `fk_user_bidang_lbe1_idx` (`id_bidang` ASC),
  INDEX `fk_user_lab1_idx` (`id_lab` ASC),
  CONSTRAINT `fk_user_bidang_lbe1`
    FOREIGN KEY (`id_bidang`)
    REFERENCES `lberepo`.`bidang_lbe` (`id_bidang`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_lab1`
    FOREIGN KEY (`id_lab`)
    REFERENCES `lberepo`.`lab` (`id_lab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lberepo`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lberepo`.`event` ;

CREATE TABLE IF NOT EXISTS `lberepo`.`event` (
  `id_event` INT NOT NULL AUTO_INCREMENT,
  `nama_event` VARCHAR(100) NOT NULL,
  `tanggal_event` TIMESTAMP NOT NULL,
  `pemateri_event` VARCHAR(100) NOT NULL,
  `id_lab` INT NOT NULL,
  PRIMARY KEY (`id_event`),
  INDEX `fk_event_lab1_idx` (`id_lab` ASC),
  CONSTRAINT `fk_event_lab1`
    FOREIGN KEY (`id_lab`)
    REFERENCES `lberepo`.`lab` (`id_lab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lberepo`.`user_event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lberepo`.`user_event` ;

CREATE TABLE IF NOT EXISTS `lberepo`.`user_event` (
  `nrp_user` CHAR(11) NOT NULL,
  `id_event` INT NOT NULL,
  `id_user_event` INT NOT NULL AUTO_INCREMENT,
  `catatan_event` LONGTEXT NULL,
  INDEX `fk_user_has_event_event1_idx` (`id_event` ASC),
  INDEX `fk_user_has_event_user1_idx` (`nrp_user` ASC),
  PRIMARY KEY (`id_user_event`),
  CONSTRAINT `fk_user_has_event_user1`
    FOREIGN KEY (`nrp_user`)
    REFERENCES `lberepo`.`user` (`nrp_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_event_event1`
    FOREIGN KEY (`id_event`)
    REFERENCES `lberepo`.`event` (`id_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `lberepo`.`feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lberepo`.`feedback` ;

CREATE TABLE IF NOT EXISTS `lberepo`.`feedback` (
  `nrp_user` CHAR(11) NOT NULL,
  `id_event` INT NOT NULL,
  `id_feedback` INT NOT NULL AUTO_INCREMENT,
  `isi_feedback` LONGTEXT NULL,
  INDEX `fk_user_has_event_event1_idx` (`id_event` ASC),
  INDEX `fk_user_has_event_user1_idx` (`nrp_user` ASC),
  PRIMARY KEY (`id_feedback`),
  CONSTRAINT `fk_user_has_event_user10`
    FOREIGN KEY (`nrp_user`)
    REFERENCES `lberepo`.`user` (`nrp_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_event_event10`
    FOREIGN KEY (`id_event`)
    REFERENCES `lberepo`.`event` (`id_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
